package com.so.dal.model.season;
// Generated 3.1.2017 21:20:18 by Hibernate Tools 4.3.1


import com.so.dal.model.registration.RegistrationTeam;
import com.so.dal.model.Resource;
import com.so.dal.model.Tournament;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SeasonTournament generated by hbm2java
 */
@Entity
@Table(name="seasonTournament"
    ,catalog="sport_app_dev"
)
public class SeasonTournament  implements java.io.Serializable {


     private Integer id;
     private Resource resource;
     private Season season;
     private Tournament tournament;
     private String name;
     private Set<SeasonTournamentPeriod> seasonTournamentPeriods = new HashSet<SeasonTournamentPeriod>(0);
     private Set<SeasonTournamentPenalty> seasonTournamentPenalties = new HashSet<SeasonTournamentPenalty>(0);
     private Set<SeasonTournamentGroup> seasonTournamentGroups = new HashSet<SeasonTournamentGroup>(0);
     private Set<SeasonTournamentRound> seasonTournamentRounds = new HashSet<SeasonTournamentRound>(0);
     private Set<RegistrationTeam> registrationTeams = new HashSet<RegistrationTeam>(0);
     private Set<SeasonTournamentLocation> seasonTournamentLocations = new HashSet<SeasonTournamentLocation>(0);
     private Set<SeasonTournamentSettings> seasonTournamentSettingses = new HashSet<SeasonTournamentSettings>(0);

    public SeasonTournament() {
    }

	
    public SeasonTournament(Season season, Tournament tournament, String name) {
        this.season = season;
        this.tournament = tournament;
        this.name = name;
    }
    public SeasonTournament(Resource resource, Season season, Tournament tournament, String name, Set<SeasonTournamentPeriod> seasonTournamentPeriods, Set<SeasonTournamentPenalty> seasonTournamentPenalties, Set<SeasonTournamentGroup> seasonTournamentGroups, Set<SeasonTournamentRound> seasonTournamentRounds, Set<RegistrationTeam> registrationTeams, Set<SeasonTournamentLocation> seasonTournamentLocations, Set<SeasonTournamentSettings> seasonTournamentSettingses) {
       this.resource = resource;
       this.season = season;
       this.tournament = tournament;
       this.name = name;
       this.seasonTournamentPeriods = seasonTournamentPeriods;
       this.seasonTournamentPenalties = seasonTournamentPenalties;
       this.seasonTournamentGroups = seasonTournamentGroups;
       this.seasonTournamentRounds = seasonTournamentRounds;
       this.registrationTeams = registrationTeams;
       this.seasonTournamentLocations = seasonTournamentLocations;
       this.seasonTournamentSettingses = seasonTournamentSettingses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idLogo")
    public Resource getResource() {
        return this.resource;
    }
    
    public void setResource(Resource resource) {
        this.resource = resource;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idSeason", nullable=false)
    public Season getSeason() {
        return this.season;
    }
    
    public void setSeason(Season season) {
        this.season = season;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idTournament", nullable=false)
    public Tournament getTournament() {
        return this.tournament;
    }
    
    public void setTournament(Tournament tournament) {
        this.tournament = tournament;
    }

    
    @Column(name="name", nullable=false, length=1500)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="seasonTournament")
    public Set<SeasonTournamentPeriod> getSeasonTournamentPeriods() {
        return this.seasonTournamentPeriods;
    }
    
    public void setSeasonTournamentPeriods(Set<SeasonTournamentPeriod> seasonTournamentPeriods) {
        this.seasonTournamentPeriods = seasonTournamentPeriods;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="seasonTournament")
    public Set<SeasonTournamentPenalty> getSeasonTournamentPenalties() {
        return this.seasonTournamentPenalties;
    }
    
    public void setSeasonTournamentPenalties(Set<SeasonTournamentPenalty> seasonTournamentPenalties) {
        this.seasonTournamentPenalties = seasonTournamentPenalties;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="seasonTournament")
    public Set<SeasonTournamentGroup> getSeasonTournamentGroups() {
        return this.seasonTournamentGroups;
    }
    
    public void setSeasonTournamentGroups(Set<SeasonTournamentGroup> seasonTournamentGroups) {
        this.seasonTournamentGroups = seasonTournamentGroups;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="seasonTournament")
    public Set<SeasonTournamentRound> getSeasonTournamentRounds() {
        return this.seasonTournamentRounds;
    }
    
    public void setSeasonTournamentRounds(Set<SeasonTournamentRound> seasonTournamentRounds) {
        this.seasonTournamentRounds = seasonTournamentRounds;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="seasonTournament")
    public Set<RegistrationTeam> getRegistrationTeams() {
        return this.registrationTeams;
    }
    
    public void setRegistrationTeams(Set<RegistrationTeam> registrationTeams) {
        this.registrationTeams = registrationTeams;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="seasonTournament")
    public Set<SeasonTournamentLocation> getSeasonTournamentLocations() {
        return this.seasonTournamentLocations;
    }
    
    public void setSeasonTournamentLocations(Set<SeasonTournamentLocation> seasonTournamentLocations) {
        this.seasonTournamentLocations = seasonTournamentLocations;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="seasonTournament")
    public Set<SeasonTournamentSettings> getSeasonTournamentSettingses() {
        return this.seasonTournamentSettingses;
    }
    
    public void setSeasonTournamentSettingses(Set<SeasonTournamentSettings> seasonTournamentSettingses) {
        this.seasonTournamentSettingses = seasonTournamentSettingses;
    }




}


