package com.so.dal.model.season;
// Generated 3.1.2017 21:20:18 by Hibernate Tools 4.3.1


import com.so.dal.model.game.Penalty;
import com.so.dal.model.game.GameActivity;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SeasonTournamentPenalty generated by hbm2java
 */
@Entity
@Table(name="seasonTournamentPenalty"
    ,catalog="sport_app_dev"
)
public class SeasonTournamentPenalty  implements java.io.Serializable {


     private Integer id;
     private Penalty penalty;
     private SeasonTournament seasonTournament;
     private Date penaltyTime;
     private Set<GameActivity> gameActivities = new HashSet<GameActivity>(0);

    public SeasonTournamentPenalty() {
    }

	
    public SeasonTournamentPenalty(Penalty penalty, SeasonTournament seasonTournament, Date penaltyTime) {
        this.penalty = penalty;
        this.seasonTournament = seasonTournament;
        this.penaltyTime = penaltyTime;
    }
    public SeasonTournamentPenalty(Penalty penalty, SeasonTournament seasonTournament, Date penaltyTime, Set<GameActivity> gameActivities) {
       this.penalty = penalty;
       this.seasonTournament = seasonTournament;
       this.penaltyTime = penaltyTime;
       this.gameActivities = gameActivities;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idPenalty", nullable=false)
    public Penalty getPenalty() {
        return this.penalty;
    }
    
    public void setPenalty(Penalty penalty) {
        this.penalty = penalty;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idSeasonTournament", nullable=false)
    public SeasonTournament getSeasonTournament() {
        return this.seasonTournament;
    }
    
    public void setSeasonTournament(SeasonTournament seasonTournament) {
        this.seasonTournament = seasonTournament;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="penaltyTime", nullable=false, length=8)
    public Date getPenaltyTime() {
        return this.penaltyTime;
    }
    
    public void setPenaltyTime(Date penaltyTime) {
        this.penaltyTime = penaltyTime;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="seasonTournamentPenalty")
    public Set<GameActivity> getGameActivities() {
        return this.gameActivities;
    }
    
    public void setGameActivities(Set<GameActivity> gameActivities) {
        this.gameActivities = gameActivities;
    }




}


