package com.so.dal.model.season;
// Generated 24.2.2017 14:54:46 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SeasonTournamentSettings generated by hbm2java
 */
@Entity
@Table(name="seasonTournamentSettings"
    ,catalog="sport_app_dev"
)
public class SeasonTournamentSettings  implements java.io.Serializable {


     private Integer id;
     private SeasonTournament seasonTournament;
     private String name;
     private String value;

    public SeasonTournamentSettings() {
    }

    public SeasonTournamentSettings(SeasonTournament seasonTournament, String name, String value) {
       this.seasonTournament = seasonTournament;
       this.name = name;
       this.value = value;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idSeasonTournament", nullable=false)
    public SeasonTournament getSeasonTournament() {
        return this.seasonTournament;
    }
    
    public void setSeasonTournament(SeasonTournament seasonTournament) {
        this.seasonTournament = seasonTournament;
    }

    
    @Column(name="name", nullable=false, length=1500)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="value", nullable=false, length=2000)
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }




}


