package com.so.dal.core.model.game;
// Generated 27.2.2017 18:41:18 by Hibernate Tools 4.3.1


import com.so.dal.core.model.season.SeasonTournamentPenaltySettings;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Penalty generated by hbm2java
 */
@Entity
@Table(name="penalty"
    ,catalog="sport_app_dev"
)
public class Penalty  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set<SeasonTournamentPenaltySettings> seasonTournamentPenaltySettingses = new HashSet<SeasonTournamentPenaltySettings>(0);

    public Penalty() {
    }

	
    public Penalty(String name) {
        this.name = name;
    }
    public Penalty(String name, Set<SeasonTournamentPenaltySettings> seasonTournamentPenaltySettingses) {
       this.name = name;
       this.seasonTournamentPenaltySettingses = seasonTournamentPenaltySettingses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false, length=1500)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="penalty")
    public Set<SeasonTournamentPenaltySettings> getSeasonTournamentPenaltySettingses() {
        return this.seasonTournamentPenaltySettingses;
    }
    
    public void setSeasonTournamentPenaltySettingses(Set<SeasonTournamentPenaltySettings> seasonTournamentPenaltySettingses) {
        this.seasonTournamentPenaltySettingses = seasonTournamentPenaltySettingses;
    }




}


