package com.so.dal.model.game;
// Generated 24.2.2017 14:54:46 by Hibernate Tools 4.3.1



import com.so.dal.model.Resource;
import com.so.dal.model.season.SeasonTournamentGroup;
import com.so.dal.model.Team;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CompetitorTeam generated by hbm2java
 */
@Entity
@Table(name="competitorTeam"
    ,catalog="sport_app_dev"
)
public class CompetitorTeam  implements java.io.Serializable {


     private Integer id;
     private Resource resource;
     private SeasonTournamentGroup seasonTournamentGroup;
     private Team team;
//     private Set<SportFlorbalGameActivity> sportFlorbalGameActivities = new HashSet<SportFlorbalGameActivity>(0);
//     private Set<SportFlorbalGameShots> sportFlorbalGameShotses = new HashSet<SportFlorbalGameShots>(0);
     private Set<CompetitorTeamPlayer> competitorTeamPlayers = new HashSet<CompetitorTeamPlayer>(0);
     private Set<SportFlorbalGame> sportFlorbalGamesForIdAwayTeam = new HashSet<SportFlorbalGame>(0);
     private Set<SportFlorbalGame> sportFlorbalGamesForIdHomeTeam = new HashSet<SportFlorbalGame>(0);

    public CompetitorTeam() {
    }

	
    public CompetitorTeam(Resource resource, SeasonTournamentGroup seasonTournamentGroup, Team team) {
        this.resource = resource;
        this.seasonTournamentGroup = seasonTournamentGroup;
        this.team = team;
    }
    public CompetitorTeam(Resource resource, SeasonTournamentGroup seasonTournamentGroup, Team team, Set<CompetitorTeamPlayer> competitorTeamPlayers, Set<SportFlorbalGame> sportFlorbalGamesForIdAwayTeam, Set<SportFlorbalGame> sportFlorbalGamesForIdHomeTeam) {
       this.resource = resource;
       this.seasonTournamentGroup = seasonTournamentGroup;
       this.team = team;
     //  this.sportFlorbalGameActivities = sportFlorbalGameActivities;
    //   this.sportFlorbalGameShotses = sportFlorbalGameShotses;
       this.competitorTeamPlayers = competitorTeamPlayers;
       this.sportFlorbalGamesForIdAwayTeam = sportFlorbalGamesForIdAwayTeam;
       this.sportFlorbalGamesForIdHomeTeam = sportFlorbalGamesForIdHomeTeam;
    }
    
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idLogo", nullable=false)
    public Resource getResource() {
        return this.resource;
    }
    
    public void setResource(Resource resource) {
        this.resource = resource;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idGroup", nullable=false)
    public SeasonTournamentGroup getSeasonTournamentGroup() {
        return this.seasonTournamentGroup;
    }
    
    public void setSeasonTournamentGroup(SeasonTournamentGroup seasonTournamentGroup) {
        this.seasonTournamentGroup = seasonTournamentGroup;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idTeam", nullable=false)
    public Team getTeam() {
        return this.team;
    }
    
    public void setTeam(Team team) {
        this.team = team;
    }

//@OneToMany(fetch=FetchType.LAZY, mappedBy="competitorTeam")
//    public Set<SportFlorbalGameActivity> getSportFlorbalGameActivities() {
//        return this.sportFlorbalGameActivities;
//    }
//    
//    public void setSportFlorbalGameActivities(Set<SportFlorbalGameActivity> sportFlorbalGameActivities) {
//        this.sportFlorbalGameActivities = sportFlorbalGameActivities;
//    }
//
//@OneToMany(fetch=FetchType.LAZY, mappedBy="competitorTeam")
//    public Set<SportFlorbalGameShots> getSportFlorbalGameShotses() {
//        return this.sportFlorbalGameShotses;
//    }
//    
//    public void setSportFlorbalGameShotses(Set<SportFlorbalGameShots> sportFlorbalGameShotses) {
//        this.sportFlorbalGameShotses = sportFlorbalGameShotses;
//    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="competitorTeam")
    public Set<CompetitorTeamPlayer> getCompetitorTeamPlayers() {
        return this.competitorTeamPlayers;
    }
    
    public void setCompetitorTeamPlayers(Set<CompetitorTeamPlayer> competitorTeamPlayers) {
        this.competitorTeamPlayers = competitorTeamPlayers;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="competitorTeamByIdAwayTeam")
    public Set<SportFlorbalGame> getSportFlorbalGamesForIdAwayTeam() {
        return this.sportFlorbalGamesForIdAwayTeam;
    }
    
    public void setSportFlorbalGamesForIdAwayTeam(Set<SportFlorbalGame> sportFlorbalGamesForIdAwayTeam) {
        this.sportFlorbalGamesForIdAwayTeam = sportFlorbalGamesForIdAwayTeam;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="competitorTeamByIdHomeTeam")
    public Set<SportFlorbalGame> getSportFlorbalGamesForIdHomeTeam() {
        return this.sportFlorbalGamesForIdHomeTeam;
    }
    
    public void setSportFlorbalGamesForIdHomeTeam(Set<SportFlorbalGame> sportFlorbalGamesForIdHomeTeam) {
        this.sportFlorbalGamesForIdHomeTeam = sportFlorbalGamesForIdHomeTeam;
    }




}


