package com.so.dal.core.model.season;
// Generated 27.2.2017 18:41:18 by Hibernate Tools 4.3.1


import com.so.dal.floorball.model.game.SportFlorbalGameActivity;
import com.so.dal.floorball.model.game.SportFlorbalGameShots;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SeasonTournamentPeriod generated by hbm2java
 */
@Entity
@Table(name="seasonTournamentPeriod"
    ,catalog="sport_app_dev"
)
public class SeasonTournamentPeriod  implements java.io.Serializable {


     private Integer id;
     private SeasonTournament seasonTournament;
     private String name;
     private Date length;
     private Set<SportFlorbalGameActivity> sportFlorbalGameActivities = new HashSet<SportFlorbalGameActivity>(0);
     private Set<SportFlorbalGameShots> sportFlorbalGameShotses = new HashSet<SportFlorbalGameShots>(0);

    public SeasonTournamentPeriod() {
    }

	
    public SeasonTournamentPeriod(SeasonTournament seasonTournament, String name, Date length) {
        this.seasonTournament = seasonTournament;
        this.name = name;
        this.length = length;
    }
    public SeasonTournamentPeriod(SeasonTournament seasonTournament, String name, Date length, Set<SportFlorbalGameActivity> sportFlorbalGameActivities, Set<SportFlorbalGameShots> sportFlorbalGameShotses) {
       this.seasonTournament = seasonTournament;
       this.name = name;
       this.length = length;
       this.sportFlorbalGameActivities = sportFlorbalGameActivities;
       this.sportFlorbalGameShotses = sportFlorbalGameShotses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idSeasonTournament", nullable=false)
    public SeasonTournament getSeasonTournament() {
        return this.seasonTournament;
    }
    
    public void setSeasonTournament(SeasonTournament seasonTournament) {
        this.seasonTournament = seasonTournament;
    }

    
    @Column(name="name", nullable=false, length=1500)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="length", nullable=false, length=8)
    public Date getLength() {
        return this.length;
    }
    
    public void setLength(Date length) {
        this.length = length;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="seasonTournamentPeriod")
    public Set<SportFlorbalGameActivity> getSportFlorbalGameActivities() {
        return this.sportFlorbalGameActivities;
    }
    
    public void setSportFlorbalGameActivities(Set<SportFlorbalGameActivity> sportFlorbalGameActivities) {
        this.sportFlorbalGameActivities = sportFlorbalGameActivities;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="seasonTournamentPeriod")
    public Set<SportFlorbalGameShots> getSportFlorbalGameShotses() {
        return this.sportFlorbalGameShotses;
    }
    
    public void setSportFlorbalGameShotses(Set<SportFlorbalGameShots> sportFlorbalGameShotses) {
        this.sportFlorbalGameShotses = sportFlorbalGameShotses;
    }




}


