package com.so.dal.core.model.season;
// Generated 27.2.2017 18:41:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Season generated by hbm2java
 */
@Entity
@Table(name="season"
    ,catalog="sport_app_dev"
)
public class Season  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set<SeasonTournament> seasonTournaments = new HashSet<>(0);

    public Season() {
    }

	
    public Season(String name) {
        this.name = name;
    }
    public Season(String name, Set<SeasonTournament> seasonTournaments) {
       this.name = name;
       this.seasonTournaments = seasonTournaments;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false, length=1000)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="season", orphanRemoval = true)
    public Set<SeasonTournament> getSeasonTournaments() {
        return this.seasonTournaments;
    }
    
    public void setSeasonTournaments(Set<SeasonTournament> seasonTournaments) {
        this.seasonTournaments = seasonTournaments;
    }




}


