package com.so.dal.core.model.season;
// Generated 27.2.2017 18:41:18 by Hibernate Tools 4.3.1


import com.so.dal.core.model.game.Penalty;
import com.so.dal.floorball.model.game.SportFlorbalGameActivity;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SeasonTournamentPenaltySettings generated by hbm2java
 */
@Entity
@Table(name="seasonTournamentPenaltySettings"
    ,catalog="sport_app_dev"
)
public class SeasonTournamentPenaltySettings  implements java.io.Serializable {


     private Integer id;
     private Penalty penalty;
     private SeasonTournament seasonTournament;
     private String name;
     private String value;
     private Set<SportFlorbalGameActivity> sportFlorbalGameActivities = new HashSet<>(0);

    public SeasonTournamentPenaltySettings() {
    }

	
    public SeasonTournamentPenaltySettings(Penalty penalty, SeasonTournament seasonTournament, String name, String value) {
        this.penalty = penalty;
        this.seasonTournament = seasonTournament;
        this.name = name;
        this.value = value;
    }
    public SeasonTournamentPenaltySettings(Penalty penalty, SeasonTournament seasonTournament, String name, String value, Set<SportFlorbalGameActivity> sportFlorbalGameActivities) {
       this.penalty = penalty;
       this.seasonTournament = seasonTournament;
       this.name = name;
       this.value = value;
       this.sportFlorbalGameActivities = sportFlorbalGameActivities;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idPenalty", nullable=false)
    public Penalty getPenalty() {
        return this.penalty;
    }
    
    public void setPenalty(Penalty penalty) {
        this.penalty = penalty;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idSeasonTournament", nullable=false)
    public SeasonTournament getSeasonTournament() {
        return this.seasonTournament;
    }
    
    public void setSeasonTournament(SeasonTournament seasonTournament) {
        this.seasonTournament = seasonTournament;
    }

    
    @Column(name="name", nullable=false, length=2500)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="value", nullable=false, length=2500)
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="seasonTournamentPenaltySettings",orphanRemoval=true)
    public Set<SportFlorbalGameActivity> getSportFlorbalGameActivities() {
        return this.sportFlorbalGameActivities;
    }
    
    public void setSportFlorbalGameActivities(Set<SportFlorbalGameActivity> sportFlorbalGameActivities) {
        this.sportFlorbalGameActivities = sportFlorbalGameActivities;
    }




}


