package com.so.dal.core.model.registration;
// Generated 27.2.2017 18:41:18 by Hibernate Tools 4.3.1

import com.so.dal.core.model.Resource;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.format.annotation.DateTimeFormat.ISO;

/**
 * RegistrationPlayer generated by hbm2java
 */
@Entity
@Table(name = "registrationPlayer", catalog = "sport_app_dev"
)
public class RegistrationPlayer implements java.io.Serializable {

    private Integer id;
    private RegistrationTeam registrationTeam;
    private String name;
    private String surname;
    private Date birthDate;
    private String mail;
    private String phone;
    private Boolean isStudent;
    private String sex;
    private Boolean isVerified;
    private Boolean isProfessional;
    private String note;
    private Integer number;
    private Resource photo;

    public RegistrationPlayer() {
    }

    public RegistrationPlayer(RegistrationTeam registrationTeam, String name, String surname, Boolean isStudent, String sex, Boolean isVerified, Boolean isProfessional,  int number) {
        this.registrationTeam = registrationTeam;
        this.name = name;
        this.surname = surname;
        this.isStudent = isStudent;
        this.sex = sex;
        this.isVerified = isVerified;
        this.isProfessional = isProfessional;
        this.number = number;
    }

    public RegistrationPlayer(RegistrationTeam registrationTeam, String name, String surname, Date birthDate, String mail, String phone, Boolean isStudent, String sex, Boolean isVerified, Boolean isProfessional, String note, int number, Resource photo) {
        this.registrationTeam = registrationTeam;
        this.name = name;
        this.surname = surname;
        this.birthDate = birthDate;
        this.mail = mail;
        this.phone = phone;
        this.isStudent = isStudent;
        this.sex = sex;
        this.isVerified = isVerified;
        this.isProfessional = isProfessional;
        this.note = note;
        this.number = number;
        this.photo = photo;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idRegistrationTeam", nullable = false)
    public RegistrationTeam getRegistrationTeam() {
        return this.registrationTeam;
    }

    public void setRegistrationTeam(RegistrationTeam registrationTeam) {
        this.registrationTeam = registrationTeam;
    }

    @Column(name = "name", nullable = false, length = 1500)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "surname", nullable = false, length = 1500)
    public String getSurname() {
        return this.surname;
    }

    public void setSurname(String surname) {
        this.surname = surname;
    }

   // @Temporal(TemporalType.DATE)
    @DateTimeFormat(iso = ISO.DATE, pattern ="yyyy-MM-dd")
    @Column(name = "birthDate", length = 10)
    public Date getBirthDate() {
        return this.birthDate;
    }

    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }

    @Column(name = "mail", length = 1500)
    public String getMail() {
        return this.mail;
    }

    public void setMail(String mail) {
        this.mail = mail;
    }

    @Column(name = "phone", length = 1500)
    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    @Column(name = "isStudent", nullable = false)
    public Boolean isIsStudent() {
        return this.isStudent;
    }

    public void setIsStudent(Boolean isStudent) {
        this.isStudent = isStudent;
    }

    @Column(name = "sex", nullable = false)
    public String getSex() {
        return this.sex;
    }

    public void setSex(String sex) {
        this.sex = sex;
    }

    @Column(name = "isVerified", nullable = false)
    public Boolean isIsVerified() {
        return this.isVerified;
    }

    public void setIsVerified(Boolean isVerified) {
        this.isVerified = isVerified;
    }

    @Column(name = "isProfessional", nullable = false)
    public Boolean isIsProfessional() {
        return this.isProfessional;
    }

    public void setIsProfessional(Boolean isProfessional) {
        this.isProfessional = isProfessional;
    }

    @Column(name = "note", nullable = true, length = 3000)
    public String getNote() {
        return this.note;
    }

    public void setNote(String note) {
        this.note = note;
    }

    @Column(name = "number", nullable = false)
    public int getNumber() {
        return this.number;
    }

    public void setNumber(int number) {
        this.number = number;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idPhoto", nullable = true)
    public Resource getPhoto() {
        return photo;
    }

    public void setPhoto(Resource photo) {
        this.photo = photo;
    }

}
