package com.so.dal.model.game;
// Generated 3.1.2017 21:20:18 by Hibernate Tools 4.3.1


import com.so.dal.model.Person;
import com.so.dal.model.Resource;
import com.so.dal.model.game.GamePlayer;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CompetitorTeamPlayer generated by hbm2java
 */
@Entity
@Table(name="competitorTeamPlayer"
    ,catalog="sport_app_dev"
)
public class CompetitorTeamPlayer  implements java.io.Serializable {


     private Integer id;
     private CompetitorTeam competitorTeam;
     private Person person;
     private Resource resource;
     private int number;
     private Boolean isCapitan;
     private Set<GamePlayer> gamePlayers = new HashSet<GamePlayer>(0);

    public CompetitorTeamPlayer() {
    }

	
    public CompetitorTeamPlayer(CompetitorTeam competitorTeam, Person person, Resource resource, int number, Boolean isCapitan) {
        this.competitorTeam = competitorTeam;
        this.person = person;
        this.resource = resource;
        this.number = number;
        this.isCapitan = isCapitan;
    }
    public CompetitorTeamPlayer(CompetitorTeam competitorTeam, Person person, Resource resource, int number, Boolean isCapitan, Set<GamePlayer> gamePlayers) {
       this.competitorTeam = competitorTeam;
       this.person = person;
       this.resource = resource;
       this.number = number;
       this.isCapitan = isCapitan;
       this.gamePlayers = gamePlayers;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idCompetitorTeam", nullable=false)
    public CompetitorTeam getCompetitorTeam() {
        return this.competitorTeam;
    }
    
    public void setCompetitorTeam(CompetitorTeam competitorTeam) {
        this.competitorTeam = competitorTeam;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idPerson", nullable=false)
    public Person getPerson() {
        return this.person;
    }
    
    public void setPerson(Person person) {
        this.person = person;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idPhoto", nullable=false)
    public Resource getResource() {
        return this.resource;
    }
    
    public void setResource(Resource resource) {
        this.resource = resource;
    }

    
    @Column(name="number", nullable=false)
    public int getNumber() {
        return this.number;
    }
    
    public void setNumber(int number) {
        this.number = number;
    }

    
    @Column(name="isCapitan", nullable=false)
    public Boolean isIsCapitan() {
        return this.isCapitan;
    }
    
    public void setIsCapitan(Boolean isCapitan) {
        this.isCapitan = isCapitan;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="competitorTeamPlayer")
    public Set<GamePlayer> getGamePlayers() {
        return this.gamePlayers;
    }
    
    public void setGamePlayers(Set<GamePlayer> gamePlayers) {
        this.gamePlayers = gamePlayers;
    }




}


