package com.so.dal.model.game;
// Generated 3.1.2017 21:20:18 by Hibernate Tools 4.3.1


import com.so.dal.model.Resource;
import com.so.dal.model.Team;
import com.so.dal.model.season.SeasonTournamentGroup;
import com.so.dal.model.game.Game;
import com.so.dal.model.game.GameActivity;
import com.so.dal.model.game.GameShots;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CompetitorTeam generated by hbm2java
 */
@Entity
@Table(name="competitorTeam"
    ,catalog="sport_app_dev"
)
public class CompetitorTeam  implements java.io.Serializable {


     private Integer id;
     private Resource resource;
     private SeasonTournamentGroup seasonTournamentGroup;
     private Team team;
     private Set<GameShots> gameShotses = new HashSet<GameShots>(0);
     private Set<Game> gamesForIdAwayTeam = new HashSet<Game>(0);
     private Set<Game> gamesForIdHomeTeam = new HashSet<Game>(0);
     private Set<GameActivity> gameActivities = new HashSet<GameActivity>(0);
     private Set<CompetitorTeamPlayer> competitorTeamPlayers = new HashSet<CompetitorTeamPlayer>(0);

    public CompetitorTeam() {
    }

	
    public CompetitorTeam(Resource resource, SeasonTournamentGroup seasonTournamentGroup, Team team) {
        this.resource = resource;
        this.seasonTournamentGroup = seasonTournamentGroup;
        this.team = team;
    }
    public CompetitorTeam(Resource resource, SeasonTournamentGroup seasonTournamentGroup, Team team, Set<GameShots> gameShotses, Set<Game> gamesForIdAwayTeam, Set<Game> gamesForIdHomeTeam, Set<GameActivity> gameActivities, Set<CompetitorTeamPlayer> competitorTeamPlayers) {
       this.resource = resource;
       this.seasonTournamentGroup = seasonTournamentGroup;
       this.team = team;
       this.gameShotses = gameShotses;
       this.gamesForIdAwayTeam = gamesForIdAwayTeam;
       this.gamesForIdHomeTeam = gamesForIdHomeTeam;
       this.gameActivities = gameActivities;
       this.competitorTeamPlayers = competitorTeamPlayers;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idLogo", nullable=false)
    public Resource getResource() {
        return this.resource;
    }
    
    public void setResource(Resource resource) {
        this.resource = resource;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idGroup", nullable=false)
    public SeasonTournamentGroup getSeasonTournamentGroup() {
        return this.seasonTournamentGroup;
    }
    
    public void setSeasonTournamentGroup(SeasonTournamentGroup seasonTournamentGroup) {
        this.seasonTournamentGroup = seasonTournamentGroup;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idTeam", nullable=false)
    public Team getTeam() {
        return this.team;
    }
    
    public void setTeam(Team team) {
        this.team = team;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="competitorTeam")
    public Set<GameShots> getGameShotses() {
        return this.gameShotses;
    }
    
    public void setGameShotses(Set<GameShots> gameShotses) {
        this.gameShotses = gameShotses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="competitorTeamByIdAwayTeam")
    public Set<Game> getGamesForIdAwayTeam() {
        return this.gamesForIdAwayTeam;
    }
    
    public void setGamesForIdAwayTeam(Set<Game> gamesForIdAwayTeam) {
        this.gamesForIdAwayTeam = gamesForIdAwayTeam;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="competitorTeamByIdHomeTeam")
    public Set<Game> getGamesForIdHomeTeam() {
        return this.gamesForIdHomeTeam;
    }
    
    public void setGamesForIdHomeTeam(Set<Game> gamesForIdHomeTeam) {
        this.gamesForIdHomeTeam = gamesForIdHomeTeam;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="competitorTeam")
    public Set<GameActivity> getGameActivities() {
        return this.gameActivities;
    }
    
    public void setGameActivities(Set<GameActivity> gameActivities) {
        this.gameActivities = gameActivities;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="competitorTeam")
    public Set<CompetitorTeamPlayer> getCompetitorTeamPlayers() {
        return this.competitorTeamPlayers;
    }
    
    public void setCompetitorTeamPlayers(Set<CompetitorTeamPlayer> competitorTeamPlayers) {
        this.competitorTeamPlayers = competitorTeamPlayers;
    }




}


