package com.so.dal.model.game;
// Generated 3.1.2017 21:20:18 by Hibernate Tools 4.3.1


import com.so.dal.model.season.SeasonTournamentPeriod;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * GameShots generated by hbm2java
 */
@Entity
@Table(name="gameShots"
    ,catalog="sport_app_dev"
)
public class GameShots  implements java.io.Serializable {


     private Integer id;
     private CompetitorTeam competitorTeam;
     private Game game;
     private SeasonTournamentPeriod seasonTournamentPeriod;
     private int count;

    public GameShots() {
    }

    public GameShots(CompetitorTeam competitorTeam, Game game, SeasonTournamentPeriod seasonTournamentPeriod, int count) {
       this.competitorTeam = competitorTeam;
       this.game = game;
       this.seasonTournamentPeriod = seasonTournamentPeriod;
       this.count = count;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idTeam", nullable=false)
    public CompetitorTeam getCompetitorTeam() {
        return this.competitorTeam;
    }
    
    public void setCompetitorTeam(CompetitorTeam competitorTeam) {
        this.competitorTeam = competitorTeam;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idGame", nullable=false)
    public Game getGame() {
        return this.game;
    }
    
    public void setGame(Game game) {
        this.game = game;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idPeriod", nullable=false)
    public SeasonTournamentPeriod getSeasonTournamentPeriod() {
        return this.seasonTournamentPeriod;
    }
    
    public void setSeasonTournamentPeriod(SeasonTournamentPeriod seasonTournamentPeriod) {
        this.seasonTournamentPeriod = seasonTournamentPeriod;
    }

    
    @Column(name="count", nullable=false)
    public int getCount() {
        return this.count;
    }
    
    public void setCount(int count) {
        this.count = count;
    }




}


