package com.so.dal.model.game;
// Generated 3.1.2017 21:20:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * GamePlayer generated by hbm2java
 */
@Entity
@Table(name="gamePlayer"
    ,catalog="sport_app_dev"
)
public class GamePlayer  implements java.io.Serializable {


     private Integer id;
     private CompetitorTeamPlayer competitorTeamPlayer;
     private Game game;
     private Set<GameActivity> gameActivitiesForIdPenaltyPlayer = new HashSet<GameActivity>(0);
     private Set<GameActivity> gameActivitiesForIdAssist2player = new HashSet<GameActivity>(0);
     private Set<GameActivity> gameActivitiesForIdGoalPlayer = new HashSet<GameActivity>(0);
     private Set<GameActivity> gameActivitiesForIdAssistPlayer = new HashSet<GameActivity>(0);

    public GamePlayer() {
    }

	
    public GamePlayer(CompetitorTeamPlayer competitorTeamPlayer, Game game) {
        this.competitorTeamPlayer = competitorTeamPlayer;
        this.game = game;
    }
    public GamePlayer(CompetitorTeamPlayer competitorTeamPlayer, Game game, Set<GameActivity> gameActivitiesForIdPenaltyPlayer, Set<GameActivity> gameActivitiesForIdAssist2player, Set<GameActivity> gameActivitiesForIdGoalPlayer, Set<GameActivity> gameActivitiesForIdAssistPlayer) {
       this.competitorTeamPlayer = competitorTeamPlayer;
       this.game = game;
       this.gameActivitiesForIdPenaltyPlayer = gameActivitiesForIdPenaltyPlayer;
       this.gameActivitiesForIdAssist2player = gameActivitiesForIdAssist2player;
       this.gameActivitiesForIdGoalPlayer = gameActivitiesForIdGoalPlayer;
       this.gameActivitiesForIdAssistPlayer = gameActivitiesForIdAssistPlayer;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idCompetitorTeamPlayer", nullable=false)
    public CompetitorTeamPlayer getCompetitorTeamPlayer() {
        return this.competitorTeamPlayer;
    }
    
    public void setCompetitorTeamPlayer(CompetitorTeamPlayer competitorTeamPlayer) {
        this.competitorTeamPlayer = competitorTeamPlayer;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idGame", nullable=false)
    public Game getGame() {
        return this.game;
    }
    
    public void setGame(Game game) {
        this.game = game;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="gamePlayerByIdPenaltyPlayer")
    public Set<GameActivity> getGameActivitiesForIdPenaltyPlayer() {
        return this.gameActivitiesForIdPenaltyPlayer;
    }
    
    public void setGameActivitiesForIdPenaltyPlayer(Set<GameActivity> gameActivitiesForIdPenaltyPlayer) {
        this.gameActivitiesForIdPenaltyPlayer = gameActivitiesForIdPenaltyPlayer;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="gamePlayerByIdAssist2player")
    public Set<GameActivity> getGameActivitiesForIdAssist2player() {
        return this.gameActivitiesForIdAssist2player;
    }
    
    public void setGameActivitiesForIdAssist2player(Set<GameActivity> gameActivitiesForIdAssist2player) {
        this.gameActivitiesForIdAssist2player = gameActivitiesForIdAssist2player;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="gamePlayerByIdGoalPlayer")
    public Set<GameActivity> getGameActivitiesForIdGoalPlayer() {
        return this.gameActivitiesForIdGoalPlayer;
    }
    
    public void setGameActivitiesForIdGoalPlayer(Set<GameActivity> gameActivitiesForIdGoalPlayer) {
        this.gameActivitiesForIdGoalPlayer = gameActivitiesForIdGoalPlayer;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="gamePlayerByIdAssistPlayer")
    public Set<GameActivity> getGameActivitiesForIdAssistPlayer() {
        return this.gameActivitiesForIdAssistPlayer;
    }
    
    public void setGameActivitiesForIdAssistPlayer(Set<GameActivity> gameActivitiesForIdAssistPlayer) {
        this.gameActivitiesForIdAssistPlayer = gameActivitiesForIdAssistPlayer;
    }




}


