package com.so.dal.model.game;
// Generated 3.1.2017 21:20:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * GameType generated by hbm2java
 */
@Entity
@Table(name="gameType"
    ,catalog="sport_app_dev"
)
public class GameType  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set<GameActivity> gameActivities = new HashSet<GameActivity>(0);

    public GameType() {
    }

	
    public GameType(String name) {
        this.name = name;
    }
    public GameType(String name, Set<GameActivity> gameActivities) {
       this.name = name;
       this.gameActivities = gameActivities;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false, length=1000)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="gameType")
    public Set<GameActivity> getGameActivities() {
        return this.gameActivities;
    }
    
    public void setGameActivities(Set<GameActivity> gameActivities) {
        this.gameActivities = gameActivities;
    }




}


