package com.so.dal.model.game;
// Generated 3.1.2017 21:20:18 by Hibernate Tools 4.3.1


import com.so.dal.model.season.SeasonTournamentPenalty;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Penalty generated by hbm2java
 */
@Entity
@Table(name="penalty"
    ,catalog="sport_app_dev"
)
public class Penalty  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Boolean isPlayerDown;
     private Boolean isPlayerOut;
     private Set<SeasonTournamentPenalty> seasonTournamentPenalties = new HashSet<SeasonTournamentPenalty>(0);

    public Penalty() {
    }

	
    public Penalty(String name, Boolean isPlayerDown, Boolean isPlayerOut) {
        this.name = name;
        this.isPlayerDown = isPlayerDown;
        this.isPlayerOut = isPlayerOut;
    }
    public Penalty(String name, Boolean isPlayerDown, Boolean isPlayerOut, Set<SeasonTournamentPenalty> seasonTournamentPenalties) {
       this.name = name;
       this.isPlayerDown = isPlayerDown;
       this.isPlayerOut = isPlayerOut;
       this.seasonTournamentPenalties = seasonTournamentPenalties;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false, length=1500)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="isPlayerDown", nullable=false)
    public Boolean isIsPlayerDown() {
        return this.isPlayerDown;
    }
    
    public void setIsPlayerDown(Boolean isPlayerDown) {
        this.isPlayerDown = isPlayerDown;
    }

    
    @Column(name="isPlayerOut", nullable=false)
    public Boolean isIsPlayerOut() {
        return this.isPlayerOut;
    }
    
    public void setIsPlayerOut(Boolean isPlayerOut) {
        this.isPlayerOut = isPlayerOut;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="penalty")
    public Set<SeasonTournamentPenalty> getSeasonTournamentPenalties() {
        return this.seasonTournamentPenalties;
    }
    
    public void setSeasonTournamentPenalties(Set<SeasonTournamentPenalty> seasonTournamentPenalties) {
        this.seasonTournamentPenalties = seasonTournamentPenalties;
    }




}


