package com.so.dal.core.model;
// Generated 27.2.2017 18:41:18 by Hibernate Tools 4.3.1


import com.so.dal.core.model.game.CompetitorTeam;
import com.so.dal.core.model.game.CompetitorTeamPlayer;
import com.so.dal.core.model.registration.RegistrationPlayer;
import com.so.dal.core.model.registration.RegistrationTeam;
import com.so.dal.core.model.season.SeasonTournament;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Resource generated by hbm2java
 */
@Entity
@Table(name="resource"
    ,catalog="sport_app_dev"
)
public class Resource  implements java.io.Serializable {


     private Integer id;
     private String path;
     private Set<CompetitorTeam> competitorTeams = new HashSet<>(0);
     private Set<SeasonTournament> seasonTournaments = new HashSet<>(0);
     private Set<RegistrationTeam> registrationTeams = new HashSet<>(0);
     private Set<CompetitorTeamPlayer> competitorTeamPlayers = new HashSet<>(0);
     private Set<RegistrationPlayer> registrationPlayers = new HashSet<>(0);

    public Resource() {
    }

	
    public Resource(String path) {
        this.path = path;
    }
    public Resource(String path, Set<CompetitorTeam> competitorTeams, Set<SeasonTournament> seasonTournaments, Set<RegistrationTeam> registrationTeams, Set<CompetitorTeamPlayer> competitorTeamPlayers, Set<RegistrationPlayer> registrationPlayers) {
       this.path = path;
       this.competitorTeams = competitorTeams;
       this.seasonTournaments = seasonTournaments;
       this.registrationTeams = registrationTeams;
       this.competitorTeamPlayers = competitorTeamPlayers;
       this.registrationPlayers= registrationPlayers;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="path", nullable=false, length=1500)
    public String getPath() {
        return this.path;
    }
    
    public void setPath(String path) {
        this.path = path;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="resource")
    public Set<CompetitorTeam> getCompetitorTeams() {
        return this.competitorTeams;
    }
    
    public void setCompetitorTeams(Set<CompetitorTeam> competitorTeams) {
        this.competitorTeams = competitorTeams;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="resource")
    public Set<SeasonTournament> getSeasonTournaments() {
        return this.seasonTournaments;
    }
    
    public void setSeasonTournaments(Set<SeasonTournament> seasonTournaments) {
        this.seasonTournaments = seasonTournaments;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="resource")
    public Set<RegistrationTeam> getRegistrationTeams() {
        return this.registrationTeams;
    }
    
    public void setRegistrationTeams(Set<RegistrationTeam> registrationTeams) {
        this.registrationTeams = registrationTeams;
    }


@OneToMany(fetch=FetchType.LAZY, mappedBy="resource")
    public Set<CompetitorTeamPlayer> getCompetitorTeamPlayers() {
        return this.competitorTeamPlayers;
    }
    
    public void setCompetitorTeamPlayers(Set<CompetitorTeamPlayer> competitorTeamPlayers) {
        this.competitorTeamPlayers = competitorTeamPlayers;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="photo")
    public Set<RegistrationPlayer> getRegistrationPlayers() {
        return registrationPlayers;
    }

    public void setRegistrationPlayers(Set<RegistrationPlayer> registrationPlayers) {
        this.registrationPlayers = registrationPlayers;
    }


    


}


