package com.so.dal.floorball.model.game;
// Generated 27.2.2017 18:41:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SportFlorbalGameActivityType generated by hbm2java
 */
@Entity
@Table(name="sportFlorbalGameActivityType"
    ,catalog="sport_app_dev"
)
public class SportFlorbalGameActivityType  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String showName;
     private Set<SportFlorbalGameActivity> sportFlorbalGameActivities = new HashSet<SportFlorbalGameActivity>(0);

    public SportFlorbalGameActivityType() {
    }

    public SportFlorbalGameActivityType(String name, String showName) {
        this.name = name;
        this.showName = showName;
    }

    public SportFlorbalGameActivityType(String name, String showName, Set<SportFlorbalGameActivity> sportFlorbalGameActivities) {
       this.name = name;
       this.showName = showName;
       this.sportFlorbalGameActivities = sportFlorbalGameActivities;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false, length=1000)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    @Column(name="showName", nullable=false, length=1000)
    public String getShowName() {
        return showName;
    }

    public void setShowName(String showName) {
        this.showName = showName;
    }
    
    

@OneToMany(fetch=FetchType.LAZY, mappedBy="sportFlorbalGameActivityType")
    public Set<SportFlorbalGameActivity> getSportFlorbalGameActivities() {
        return this.sportFlorbalGameActivities;
    }
    
    public void setSportFlorbalGameActivities(Set<SportFlorbalGameActivity> sportFlorbalGameActivities) {
        this.sportFlorbalGameActivities = sportFlorbalGameActivities;
    }




}


